/*
 * Segundo proyecto programado del curso de programación.
 * Universidad de Costa Rica - Sede del Pacífico Arnoldo Ferreto Segura
 */
package vista;

import controlador.Controlador_FRM_VentanaInicio;
//import modelo.Jugador_XML;
/**
 *
 * @author yirlany
 */
public class FRM_VentanaPuntajes extends javax.swing.JFrame {

    //Referencias de clase
    FRM_VentanaInicio fRM_VentanaInicio;
    
    //Constructor de la clase
    public FRM_VentanaPuntajes() {
        initComponents();
        
        this.setLocation(200, 10);
        this.jT_NombreJugador.setEditable(false);
        
    }
    
    public void mostrarPuntaje(String arregalo[]) {
        this.jT_NombreJugador.setText(arregalo[0]);
        this.jT_Puntaje.setText(arregalo[1]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_Atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jT_NombreJugador = new javax.swing.JTextField();
        jT_Puntaje = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(544, 290));
        setMinimumSize(new java.awt.Dimension(544, 290));
        setPreferredSize(new java.awt.Dimension(544, 288));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_Atras.setBackground(new java.awt.Color(245, 235, 235));
        jB_Atras.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jB_Atras.setForeground(new java.awt.Color(16, 116, 250));
        jB_Atras.setText("Atrás");
        jB_Atras.setActionCommand("Atras");
        jB_Atras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 150), new java.awt.Color(0, 255, 142), new java.awt.Color(255, 146, 0), new java.awt.Color(255, 111, 0)));
        getContentPane().add(jB_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 100, 50));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 170, 50));

        jT_NombreJugador.setBackground(new java.awt.Color(102, 102, 102));
        jT_NombreJugador.setFont(new java.awt.Font("Impact", 2, 24)); // NOI18N
        jT_NombreJugador.setForeground(new java.awt.Color(204, 204, 204));
        jT_NombreJugador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jT_NombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 340, 50));

        jT_Puntaje.setEditable(false);
        jT_Puntaje.setBackground(new java.awt.Color(249, 239, 239));
        jT_Puntaje.setFont(new java.awt.Font("Impact", 2, 48)); // NOI18N
        jT_Puntaje.setForeground(new java.awt.Color(197, 75, 237));
        jT_Puntaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jT_Puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 260, 50));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 246, 178));
        jLabel3.setText("Puntaje Final:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo-videojuego.gif"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(620, 288));
        jLabel2.setMinimumSize(new java.awt.Dimension(620, 288));
        jLabel2.setPreferredSize(new java.awt.Dimension(620, 288));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jB_Atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jT_NombreJugador;
    private javax.swing.JTextField jT_Puntaje;
    // End of variables declaration//GEN-END:variables
}
